name: Android Pull Request
on:
  push:
  pull_request:
         branches:
          - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Code from VCS
      uses: actions/checkout@v2
    - name: Set Up JDK              
      uses: actions/setup-java@v1.4.3
      with:
       java-version: 1.8
    - name: Perform lint check
      run: ./gradlew -lint
    - name: Building android app
      run: ./gradlew assemble
    - name: Junit Testing
      run: ./gradlew test
